version: '3'

services:
  nginx:
    image: nginx:mainline
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx.bundle.crt:/etc/nginx/conf.d/nginx.crt
      - ./nginx.key:/etc/nginx/conf.d/nginx.key
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: bin.Dockerfile

  client:
    build:
      context: .
      dockerfile: bin.Dockerfile
    environment:
      - CLIENT=1
      - CONCURRENT
      - BODY
      - JOBS
      - REQUESTS
      - GODEBUG
      - HTTP2_TRANSPORT
      - TLS_SKIP_VERIFY
    depends_on:
      - nginx
